# Generated by Django 4.1.2 on 2022-10-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
