# Generated by Django 4.1.2 on 2022-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
